version: '3.7'

services:
  zcore-getkey:
    hostname: zcore-getkey
    image: ethereum/client-go
    build:
      context: . 
    command:
      --datadir=/root/.ethereum/ account new --password /root/.ethereum/keystore/pass.pwd
    ports:
      - "8545:8545"
    volumes:
      - ./genkey:/root/.ethereum
    networks:
      priv-eth-net:

networks:
  priv-eth-net:
    driver: bridge
    ipam:
      config:
      - subnet: 172.16.254.0/28
